Midori/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from Feed.views import PublicacionListView, PublicacionDetailView

from django.contrib import admin


urlpatterns = patterns(
    "",
    url(r"^$", 'Feed.views.home', name="home"),
    url(r'^categoria/(\d+)$', 'Feed.views.categoria', name='categoria'),
    url(r'^post/(\d+)$', 'Feed.views.post', name='post'),
    url(r"^admin/", include(admin.site.urls)),

    #Sistema de usuarios
    url(r"^account/", include("account.urls")),
    url(r'^usuario/(\d+)$', 'Feed.views.usuario', name='usuario'),
    

    #Sistema de feed
    url(r'^feed/$', PublicacionListView.as_view(), name='publicaciones'),
    url(r'^feed/(?P<pk>[\d]+)$', PublicacionDetailView.as_view(), name='publicaciones'),
    url(r'^activity/', include('actstream.urls')),
    
    #Sistema de follows
    url(r'^seguir/(?P<id_usuario>\d+)$', 'Feed.views.seguir', name='seguir'),
    url(r'^noseguir/(?P<id_usuario>\d+)$', 'Feed.views.noseguir', name='noseguir'),
    
    #Sistema de favoritos
    url(r'^favorito/(?P<id_publicacion>\d+)$', 'Feed.views.favorito', name='favorito'),
    url(r'^nofavorito/(?P<id_publicacion>\d+)$', 'Feed.views.nofavorito', name='nofavorito'),
    
    #Sistema de Likes
    url(r'^mas/(?P<id_publicacion>\d+)$', 'Feed.views.mas', name='mas'),
    url(r'^nomas/(?P<id_publicacion>\d+)$', 'Feed.views.nomas', name='nomas'),

)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_comments/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('django_comments.views',
    url(r'^post/$', 'comments.post_comment', name='comments-post-comment'),
    url(r'^posted/$', 'comments.comment_done', name='comments-comment-done'),
    url(r'^flag/(\d+)/$', 'moderation.flag', name='comments-flag'),
    url(r'^flagged/$', 'moderation.flag_done', name='comments-flag-done'),
    url(r'^delete/(\d+)/$', 'moderation.delete', name='comments-delete'),
    url(r'^deleted/$', 'moderation.delete_done', name='comments-delete-done'),
    url(r'^approve/(\d+)/$', 'moderation.approve', name='comments-approve'),
    url(r'^approved/$', 'moderation.approve_done', name='comments-approve-done'),
)

urlpatterns += patterns('',
    url(r'^cr/(\d+)/(.+)/$', 'django.contrib.contenttypes.views.shortcut',
        name='comments-url-redirect'),
)

django_comments/models.py
from django.conf import settings

try:
    from django.contrib.contenttypes.fields import GenericForeignKey
except ImportError:
    from django.contrib.contenttypes.generic import GenericForeignKey

from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.core import urlresolvers
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from django_comments.managers import CommentManager

COMMENT_MAX_LENGTH = getattr(settings, 'COMMENT_MAX_LENGTH', 3000)


class BaseCommentAbstractModel(models.Model):
    """
    An abstract base class that any custom comment models probably should
    subclass.
    """

    # Content-object field
    content_type = models.ForeignKey(ContentType,
                                     verbose_name=_('content type'),
                                     related_name="content_type_set_for_%(class)s")
    object_pk = models.TextField(_('object ID'))
    content_object = GenericForeignKey(ct_field="content_type", fk_field="object_pk")

    # Metadata about the comment
    site = models.ForeignKey(Site)

    class Meta:
        abstract = True

    def get_content_object_url(self):
        """
        Get a URL suitable for redirecting to the content object.
        """
        return urlresolvers.reverse(
            "comments-url-redirect",
            args=(self.content_type_id, self.object_pk)
        )


@python_2_unicode_compatible
class Comment(BaseCommentAbstractModel):
    """
    A user comment about some object.
    """

    # Who posted this comment? If ``user`` is set then it was an authenticated
    # user; otherwise at least user_name should have been set and the comment
    # was posted by a non-authenticated user.
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('user'),
                             blank=True, null=True, related_name="%(class)s_comments")
    user_name = models.CharField(_("user's name"), max_length=50, blank=True)
    # Explicit `max_length` to apply both to Django 1.7 and 1.8+.
    user_email = models.EmailField(_("user's email address"), max_length=254,
                                   blank=True)
    user_url = models.URLField(_("user's URL"), blank=True)

    comment = models.TextField(_('comment'), max_length=COMMENT_MAX_LENGTH)

    # Metadata about the comment
    submit_date = models.DateTimeField(_('date/time submitted'), default=None)
    ip_address = models.GenericIPAddressField(_('IP address'), unpack_ipv4=True, blank=True, null=True)
    is_public = models.BooleanField(_('is public'), default=True,
                                    help_text=_('Uncheck this box to make the comment effectively '
                                                'disappear from the site.'))
    is_removed = models.BooleanField(_('is removed'), default=False,
                                     help_text=_('Check this box if the comment is inappropriate. '
                                                 'A "This comment has been removed" message will '
                                                 'be displayed instead.'))

    # Manager
    objects = CommentManager()

    class Meta:
        db_table = "django_comments"
        ordering = ('submit_date',)
        permissions = [("can_moderate", "Can moderate comments")]
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

    def __str__(self):
        return "%s: %s..." % (self.name, self.comment[:50])

    def save(self, *args, **kwargs):
        if self.submit_date is None:
            self.submit_date = timezone.now()
        super(Comment, self).save(*args, **kwargs)

    def _get_userinfo(self):
        """
        Get a dictionary that pulls together information about the poster
        safely for both authenticated and non-authenticated comments.

        This dict will have ``name``, ``email``, and ``url`` fields.
        """
        if not hasattr(self, "_userinfo"):
            userinfo = {
                "name": self.user_name,
                "email": self.user_email,
                "url": self.user_url
            }
            if self.user_id:
                u = self.user
                if u.email:
                    userinfo["email"] = u.email

                # If the user has a full name, use that for the user name.
                # However, a given user_name overrides the raw user.username,
                # so only use that if this comment has no associated name.
                if u.get_full_name():
                    userinfo["name"] = self.user.get_full_name()
                elif not self.user_name:
                    userinfo["name"] = u.get_username()
            self._userinfo = userinfo
        return self._userinfo

    userinfo = property(_get_userinfo, doc=_get_userinfo.__doc__)

    def _get_name(self):
        return self.userinfo["name"]

    def _set_name(self, val):
        if self.user_id:
            raise AttributeError(_("This comment was posted by an authenticated "
                                   "user and thus the name is read-only."))
        self.user_name = val

    name = property(_get_name, _set_name, doc="The name of the user who posted this comment")

    def _get_email(self):
        return self.userinfo["email"]

    def _set_email(self, val):
        if self.user_id:
            raise AttributeError(_("This comment was posted by an authenticated "
                                   "user and thus the email is read-only."))
        self.user_email = val

    email = property(_get_email, _set_email, doc="The email of the user who posted this comment")

    def _get_url(self):
        return self.userinfo["url"]

    def _set_url(self, val):
        self.user_url = val

    url = property(_get_url, _set_url, doc="The URL given by the user who posted this comment")

    def get_absolute_url(self, anchor_pattern="#c%(id)s"):
        return self.get_content_object_url() + (anchor_pattern % self.__dict__)

    def get_as_text(self):
        """
        Return this comment as plain text.  Useful for emails.
        """
        d = {
            'user': self.user or self.name,
            'date': self.submit_date,
            'comment': self.comment,
            'domain': self.site.domain,
            'url': self.get_absolute_url()
        }
        return _('Posted by %(user)s at %(date)s\n\n%(comment)s\n\nhttp://%(domain)s%(url)s') % d


@python_2_unicode_compatible
class CommentFlag(models.Model):
    """
    Records a flag on a comment. This is intentionally flexible; right now, a
    flag could be:

        * A "removal suggestion" -- where a user suggests a comment for (potential) removal.

        * A "moderator deletion" -- used when a moderator deletes a comment.

    You can (ab)use this model to add other flags, if needed. However, by
    design users are only allowed to flag a comment with a given flag once;
    if you want rating look elsewhere.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('user'), related_name="comment_flags")
    comment = models.ForeignKey(Comment, verbose_name=_('comment'), related_name="flags")
    flag = models.CharField(_('flag'), max_length=30, db_index=True)
    flag_date = models.DateTimeField(_('date'), default=None)

    # Constants for flag types
    SUGGEST_REMOVAL = "removal suggestion"
    MODERATOR_DELETION = "moderator deletion"
    MODERATOR_APPROVAL = "moderator approval"

    class Meta:
        db_table = 'django_comment_flags'
        unique_together = [('user', 'comment', 'flag')]
        verbose_name = _('comment flag')
        verbose_name_plural = _('comment flags')

    def __str__(self):
        return "%s flag of comment ID %s by %s" % (
            self.flag, self.comment_id, self.user.get_username()
        )

    def save(self, *args, **kwargs):
        if self.flag_date is None:
            self.flag_date = timezone.now()
        super(CommentFlag, self).save(*args, **kwargs)

django_comments/views/comments.py
from __future__ import absolute_import

from django import http
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.db import models
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import render_to_string
from django.utils.html import escape
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST

try:
    from django.apps import apps
except ImportError:
    from django.db import models as apps

import django_comments
from django_comments import signals
from django_comments.views.utils import next_redirect, confirmation_view


class CommentPostBadRequest(http.HttpResponseBadRequest):
    """
    Response returned when a comment post is invalid. If ``DEBUG`` is on a
    nice-ish error message will be displayed (for debugging purposes), but in
    production mode a simple opaque 400 page will be displayed.
    """

    def __init__(self, why):
        super(CommentPostBadRequest, self).__init__()
        if settings.DEBUG:
            self.content = render_to_string("comments/400-debug.html", {"why": why})


@csrf_protect
@require_POST
def post_comment(request, next=None, using=None):
    """
    Post a comment.

    HTTP POST is required. If ``POST['submit'] == "preview"`` or if there are
    errors a preview template, ``comments/preview.html``, will be rendered.
    """
    # Fill out some initial data fields from an authenticated user, if present
    data = request.POST.copy()
    if request.user.is_authenticated():
        if not data.get('name', ''):
            data["name"] = request.user.get_full_name() or request.user.get_username()
        if not data.get('email', ''):
            data["email"] = request.user.email

    # Look up the object we're trying to comment about
    ctype = data.get("content_type")
    object_pk = data.get("object_pk")
    if ctype is None or object_pk is None:
        return CommentPostBadRequest("Missing content_type or object_pk field.")
    try:
        model = apps.get_model(*ctype.split(".", 1))
        target = model._default_manager.using(using).get(pk=object_pk)
    except TypeError:
        return CommentPostBadRequest(
            "Invalid content_type value: %r" % escape(ctype))
    except AttributeError:
        return CommentPostBadRequest(
            "The given content-type %r does not resolve to a valid model." % escape(ctype))
    except ObjectDoesNotExist:
        return CommentPostBadRequest(
            "No object matching content-type %r and object PK %r exists." % (
                escape(ctype), escape(object_pk)))
    except (ValueError, ValidationError) as e:
        return CommentPostBadRequest(
            "Attempting go get content-type %r and object PK %r exists raised %s" % (
                escape(ctype), escape(object_pk), e.__class__.__name__))

    # Do we want to preview the comment?
    preview = "preview" in data

    # Construct the comment form
    form = django_comments.get_form()(target, data=data)

    # Check security information
    if form.security_errors():
        return CommentPostBadRequest(
            "The comment form failed security verification: %s" % escape(str(form.security_errors())))

    # If there are errors or if we requested a preview show the comment
    if form.errors or preview:
        template_list = [
            # These first two exist for purely historical reasons.
            # Django v1.0 and v1.1 allowed the underscore format for
            # preview templates, so we have to preserve that format.
            "comments/%s_%s_preview.html" % (model._meta.app_label, model._meta.model_name),
            "comments/%s_preview.html" % model._meta.app_label,
            # Now the usual directory based template hierarchy.
            "comments/%s/%s/preview.html" % (model._meta.app_label, model._meta.model_name),
            "comments/%s/preview.html" % model._meta.app_label,
            "comments/preview.html",
        ]
        return render_to_response(
            template_list, {
                "comment": form.data.get("comment", ""),
                "form": form,
                "next": data.get("next", next),
            },
            RequestContext(request, {})
        )

    # Otherwise create the comment
    comment = form.get_comment_object()
    comment.ip_address = request.META.get("REMOTE_ADDR", None)
    if request.user.is_authenticated():
        comment.user = request.user

    # Signal that the comment is about to be saved
    responses = signals.comment_will_be_posted.send(
        sender=comment.__class__,
        comment=comment,
        request=request
    )

    for (receiver, response) in responses:
        if response is False:
            return CommentPostBadRequest(
                "comment_will_be_posted receiver %r killed the comment" % receiver.__name__)

    # Save the comment and signal that it was saved
    comment.save()
    signals.comment_was_posted.send(
        sender=comment.__class__,
        comment=comment,
        request=request
    )

    return next_redirect(request, fallback=next or 'comments-comment-done',
                         c=comment._get_pk_val())


comment_done = confirmation_view(
    template="comments/posted.html",
    doc="""Display a "comment was posted" success page."""
)

django_comments/templates/comments/400-debug.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <title>Comment post not allowed (400)</title>
  <meta name="robots" content="NONE,NOARCHIVE"/>
  <style type="text/css">
    <
    !
    [CDATA[
    html * {
      padding: 0;
      margin: 0;
    }

    body * {
      padding: 10px 20px;
    }

    body * * {
      padding: 0;
    }

    body {
      font: small sans-serif;
      background: #eee;
    }

    body > div {
      border-bottom: 1px solid #ddd;
    }

    h1 {
      font-weight: normal;
      margin-bottom: .4em;
    }

    h1 span {
      font-size: 60%;
      color: #666;
      font-weight: normal;
    }

    table {
      border: none;
      border-collapse: collapse;
      width: 100%;
    }

    td, th {
      vertical-align: top;
      padding: 2px 3px;
    }

    th {
      width: 12em;
      text-align: right;
      color: #666;
      padding-right: .5em;
    }

    #info {
      background: #f6f6f6;
    }

    #info ol {
      margin: 0.5em 4em;
    }

    #info ol li {
      font-family: monospace;
    }

    #summary {
      background: #ffc;
    }

    #explanation {
      background: #eee;
      border-bottom: 0px none;
    }

    ]
    ]
    >
  </style>
</head>
<body>
<div id="summary">
  <h1>Comment post not allowed <span>(400)</span></h1>
  <table class="meta">
    <tr>
      <th>Why:</th>
      <td>{{ why }}</td>
    </tr>
  </table>
</div>
<div id="info">
  <p>
    The comment you tried to post to this view wasn't saved because something
    tampered with the security information in the comment form. The message
    above should explain the problem, or you can check the <a
          href="http://docs.djangoproject.com/en/dev/ref/contrib/comments/">comment
    documentation</a> for more help.
  </p>
</div>

<div id="explanation">
  <p>
    You're seeing this error because you have <code>DEBUG = True</code> in
    your Django settings file. Change that to <code>False</code>, and Django
    will display a standard 400 error page.
  </p>
</div>
</body>
</html>

django_comments/templates/comments/approve.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Approve a comment" %}{% endblock %}

{% block content %}
  <h1>{% trans "Really make this comment public?" %}</h1>
  <blockquote>{{ comment|linebreaks }}</blockquote>
  <form action="." method="post">{% csrf_token %}
    {% if next %}
      <div><input type="hidden" name="next" value="{{ next }}" id="next"/></div>{% endif %}
    <p class="submit">
      <input type="submit" name="submit" value="{% trans "Approve" %}"/> or <a href="{{ comment.get_absolute_url }}">cancel</a>
    </p>
  </form>
{% endblock %}

django_comments/templates/comments/approved.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Thanks for approving" %}.{% endblock %}

{% block content %}
  <h1>{% trans "Thanks for taking the time to improve the quality of discussion on our site" %}.</h1>
{% endblock %}

django_comments/templates/comments/base.html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

django_comments/templates/comments/delete.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Remove a comment" %}{% endblock %}

{% block content %}
  <h1>{% trans "Really remove this comment?" %}</h1>
  <blockquote>{{ comment|linebreaks }}</blockquote>
  <form action="." method="post">{% csrf_token %}
    {% if next %}
      <div><input type="hidden" name="next" value="{{ next }}" id="next"/></div>{% endif %}
    <p class="submit">
      <input type="submit" name="submit" value="{% trans "Remove" %}"/> or <a href="{{ comment.get_absolute_url }}">cancel</a>
    </p>
  </form>
{% endblock %}

django_comments/templates/comments/deleted.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Thanks for removing" %}.{% endblock %}

{% block content %}
  <h1>{% trans "Thanks for taking the time to improve the quality of discussion on our site" %}.</h1>
{% endblock %}

django_comments/templates/comments/flag.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Flag this comment" %}{% endblock %}

{% block content %}
  <h1>{% trans "Really flag this comment?" %}</h1>
  <blockquote>{{ comment|linebreaks }}</blockquote>
  <form action="." method="post">{% csrf_token %}
    {% if next %}
      <div><input type="hidden" name="next" value="{{ next }}" id="next"/></div>{% endif %}
    <p class="submit">
      <input type="submit" name="submit" value="{% trans "Flag" %}"/> or <a
            href="{{ comment.get_absolute_url }}">cancel</a>
    </p>
  </form>
{% endblock %}

django_comments/templates/comments/flagged.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Thanks for flagging" %}.{% endblock %}

{% block content %}
  <h1>{% trans "Thanks for taking the time to improve the quality of discussion on our site" %}.</h1>
{% endblock %}

django_comments/templates/comments/form.html
{% load comments i18n %}
<form action="{% comment_form_target %}" method="post">{% csrf_token %}
  {% if next %}
    <div><input type="hidden" name="next" value="{{ next }}"/></div>{% endif %}
  {% for field in form %}
    {% if field.is_hidden %}
      <div>{{ field }}</div>
    {% else %}
      {% if field.errors %}{{ field.errors }}{% endif %}
      <p
              {% if field.errors %} class="error"{% endif %}
              {% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
        {{ field.label_tag }} {{ field }}
      </p>
    {% endif %}
  {% endfor %}
  <p class="submit">
    <input type="submit" name="post" class="submit-post" value="{% trans "Post" %}"/>
    <input type="submit" name="preview" class="submit-preview" value="{% trans "Preview" %}"/>
  </p>
</form>

django_comments/templates/comments/list.html
<dl id="comments">
  {% for comment in comment_list %}
    <dt id="c{{ comment.id }}">
      {{ comment.submit_date }} - {{ comment.name }}
    </dt>
    <dd>
      <p>{{ comment.comment }}</p>
    </dd>
  {% endfor %}
</dl>

django_comments/templates/comments/posted.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Thanks for commenting" %}.{% endblock %}

{% block content %}
  <h1>{% trans "Thank you for your comment" %}.</h1>
{% endblock %}

django_comments/templates/comments/preview.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Preview your comment" %}{% endblock %}

{% block content %}
  {% load comments %}
  <form action="{% comment_form_target %}" method="post">{% csrf_token %}
    {% if next %}
      <div><input type="hidden" name="next" value="{{ next }}"/></div>{% endif %}
    {% if form.errors %}
      <h1>{% blocktrans count counter=form.errors|length %}Please correct the error below{% plural %}Please correct the
        errors below{% endblocktrans %}</h1>
    {% else %}
      <h1>{% trans "Preview your comment" %}</h1>
      <blockquote>{{ comment|linebreaks }}</blockquote>
      <p>
        {% trans "and" %} <input type="submit" name="submit" class="submit-post" value="{% trans "Post your comment" %}"
                                 id="submit"/> {% trans "or make changes" %}:
      </p>
    {% endif %}
    {% for field in form %}
      {% if field.is_hidden %}
        <div>{{ field }}</div>
      {% else %}
        {% if field.errors %}{{ field.errors }}{% endif %}
        <p
                {% if field.errors %} class="error"{% endif %}
                {% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
          {{ field.label_tag }} {{ field }}
        </p>
      {% endif %}
    {% endfor %}
    <p class="submit">
      <input type="submit" name="submit" class="submit-post" value="{% trans "Post" %}"/>
      <input type="submit" name="preview" class="submit-preview" value="{% trans "Preview" %}"/>
    </p>
  </form>
{% endblock %}